# fly.toml app configuration file generated for gitvista-floral-forest-6888 on 2026-02-21T14:52:35-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gitvista-floral-forest-6888'
primary_region = 'iad'

[build]

[env]
  GITVISTA_DATA_DIR = '/data/repos'
  GITVISTA_HOST = '0.0.0.0'
  GITVISTA_LOG_FORMAT = 'json'
  GITVISTA_LOG_LEVEL = 'info'
  GITVISTA_PORT = '8080'

[[mounts]]
  source = 'gitvista_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 500
    soft_limit = 400

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 1024
